server:
  port: 8080

spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/liquibase.xml

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5432/nova_shoe
    username: ${postgres-username}
    password: ${postgres-password}
    driver-class-name: org.postgresql.Driver

  application:
    name: backend
    version: 0.0.1-SNAPSHOT

security:
  dashboard:
    secret: ${dashboard-jwt-secret}
    access-token-expiration: ${dashboard-access-token-expiration}
    refresh-token-expiration: ${dashboard-refresh-token-expiration}
    issuer: nova-shoe-backend
    audience: nova-shoe-dashboard