server:
  port: 8080

spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/liquibase.xml

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5432/nova_shoe
    username: ${postgres-username}
    password: ${postgres-password}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  application:
    name: backend
    version: 0.0.1-SNAPSHOT

security:
  dashboard:
    secret: ${dashboard-jwt-secret}
    access-token-expiration: ${dashboard-access-token-expiration}
    refresh-token-expiration: ${dashboard-refresh-token-expiration}
    issuer: nova-shoe-backend
    audience: nova-shoe-dashboard

  store:
    secret: ${store-jwt-secret}
    access-token-expiration: ${store-access-token-expiration}
    refresh-token-expiration: ${store-refresh-token-expiration}
    issuer: nova-shoe-backend
    audience: nova-shoe-store

cloudflare:
  r2:
    access-key: ${cloudflare-r2-access-key}
    secret-key: ${cloudflare-r2-secret-key}
    account-id: ${cloudflare-r2-account-id}
    bucketName: ${cloudflare-r2-bucket-name}
    public-url: ${cloudflare-r2-public-url}
    region: ${cloudflare-r2-region}
